language: python
dist: trusty
os: linux
python:
  - "3.6"

install:
  - pwd
  - pip install .
  - pip install pytest
  - pip freeze

script:
  - pwd
  - pytest tf-yarn/tests

notifications:
  email: false
