language: python
dist: trusty
os: linux
python:
  - "3.6"

install:
  - cd ~/tf-yarn
  - pip install -r requirements.txt
  - pip install -v --no-deps -e .
  - pip install pytest
  - pip freeze

script:
  - pytest tf-yarn/tests -vv

notifications:
  email: false
